version: '3'

services:
  tournament-api:
    container_name: api
    build: ./api
    ports:
      - 3001:3001
    volumes:
      - "./api:/app"
      - "/app/node_modules"
    command: npm start
  tournament-front:
    container_name: web
    build: ./front
    ports:
     - 3000:3000
    volumes:
     - "./front:/app"
     - "/app/node_modules"
    command: npm start
    links:
     - "tournament-api"
    environment:
     - REACT_APP_API_HOST=http://localhost:3001
