version: '3'

services:

  tournament-api:

    container_name: api
    build: .
    ports:
      - 3001:3000
    volumes:
      - "./api:/app"
    command: npm start

  tournament-front:

    container_name: web
    build: .
    ports:
     - 3000:3000
    volumes:
     - "./front:/app"
    command: npm start
    environment:
     - REACT_APP_API_HOST=${REACT_APP_API_HOST}
